blog/urls.py
# -*- coding: utf-8 -*-

from django.urls import path
from . import views as BlogViews

app_name = 'blog'

urlpatterns = [
    path('', BlogViews.Index().index, name='Index'),
    path('chat/', BlogViews.chat_view, name='chat'),
    path('send_message/', BlogViews.send_message, name='send_message'),
    path('archives/', BlogViews.Archives, name='Archives'),
    path('tutorial/', BlogViews.Tutorial, name='Tutorial'),
    path('about/', BlogViews.About, name='About'),
    path('project/', BlogViews.Project, name='Project'),
    path('tags/<tag>/', BlogViews.Index().tags, name='tags'),
    path('post/<int:pk>/', BlogViews.Detail, name='post'),
    path('content.json/',BlogViews.search, name='search'),


]

comment/urls.py
# -*- coding: utf-8 -*-

from django.urls import path
from .views import CommentView


app_name = 'comment'

urlpatterns = [
    # 发表评论
    path('post-comment/<int:post_id>/', CommentView.as_view(), name='post_comment'),
]

www/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home.as_view(), name='home'),

    path('blog/', include('blog.urls')),
    path('comment/', include('comment.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'www.views.page_not_found'
handler500 = 'www.views.server_error'

comment/models.py
# -*- coding:utf-8 -*-
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from blog.models import Post
import os
import random

app_name = 'comment'


class Comment(models.Model):
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, blank=True, null=True, verbose_name=u'文章')
    parent_id = models.IntegerField(blank=True, default=0, verbose_name=u'父级评论id')
    reply_id = models.IntegerField(blank=True, default=0, verbose_name=u'回复id')

    content = RichTextUploadingField(verbose_name=u'评论内容', config_name='comment')
    comment_type = models.CharField(
        max_length=10,
        choices=(('comment', u'评论'),
                 ('reply', u'回复'),
                 ),
        default='comment',
        verbose_name=u'评论类型',
    )
    add_time = models.DateTimeField(blank=True, auto_now_add=True, verbose_name=u'评论时间')

    mail = models.EmailField(verbose_name=u'评论用户邮箱')
    nick = models.CharField(max_length=20, verbose_name=u'评论用户名')

    to_mail = models.EmailField(null=True, blank=True, verbose_name=u'目标用户邮箱')
    to_nick = models.CharField(max_length=20, null=True, blank=True, verbose_name=u'目标用户名')
    browser = models.CharField(max_length=100, null=True, blank=True, verbose_name=u'浏览器')
    client = models.CharField(max_length=100, null=True, blank=True, verbose_name=u'客户端')
    avatar = models.CharField(max_length=200, null=True, blank=True, verbose_name=u'头像')

    is_show = models.BooleanField(default=True, verbose_name=u'是否显示评论')

    def __str__(self):
        return str(self.post_id)

    class Meta:
        ordering = ['post_id', 'add_time']
        verbose_name = u'评论内容'
        verbose_name_plural = u'评论内容'

    def save(self, *args, **kwargs):
        self.avatar = get_avatar(self.mail)  # 获取头像
        super().save(*args, **kwargs)


# 获取评论用户头像
def get_avatar(mail):
    def get_avatar_files(file_path):  # 获取路径中的头像文件名
        if os.path.exists(file_path):
            files_list = []
            for root, dirs, files in os.walk(file_path):
                for file in files:
                    # 筛选图片类型
                    file_type = os.path.splitext(file)[1]
                    if file_type.lower() in ['.png', '.jpg', '.jpeg']:
                        files_list.append(file)
            return files_list
        else:
            return []

    try:
        # 1、判断该用户头像是否存在
        comment = Comment.objects.filter(mail=mail).first()
        if comment:
            if comment.avatar:
                return comment.avatar

        # 2、如果是新用户，则随机分配一个头像
        path = r'static/comment_avatar'  # 静态文件static路径
        comment_avatar_list = get_avatar_files(file_path=path)

        if not comment_avatar_list:  # 如果路径中匹配不到，则从app的静态文件路径查找
            comment_avatar_list = get_avatar_files(file_path='comment/' + path)

        if comment_avatar_list:
            comment_avatar = random.choice(comment_avatar_list)  # 随机取一个头像分配给评论用户
            return '/{0}/{1}'.format(path, comment_avatar)

        return ''
    except BaseException as e:
        print(e)
        return ''

comment/forms.py
# -*- coding: utf-8 -*-

from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

blog/views.py
# _*_ coding:utf-8 _*_

from django.shortcuts import render, get_object_or_404
from blog.models import Post, Tag
from comment.models import Comment
from comment.forms import CommentForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.db.models.aggregates import Count
import json
from django.http import HttpResponse, JsonResponse
from www.views import page_not_found
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import csrf_protect
import websockets
import datetime
import hmac
import base64
from urllib.parse import urlencode
from django.conf import settings


# 获取某篇文章的评论回复内容
def comment_reply_content(post_id):
    # 评论
    comments = Comment.objects.filter(is_show=True, post_id=post_id, comment_type='comment').order_by('pk')
    comments_dict = {'comments': {}, 'count': 0}
    for comment in comments:
        comments_dict['comments'][comment.id] = {
            'comment': {
                'id': comment.pk,
                'post_id': comment.post_id,
                'add_time': comment.add_time,
                'content': comment.content,
                'parent_id': comment.parent_id,
                'reply_id': comment.reply_id,
                'nick': comment.nick,
                'browser': comment.browser,
                'client': comment.client,
                'avatar': comment.avatar,
            },
            'reply': [],
        }
    # 回复
    replys = Comment.objects.filter(is_show=True, post_id=post_id, comment_type='reply').order_by('pk')
    for reply in replys:
        if reply.parent_id in comments_dict['comments'].keys():
            comments_dict['comments'][reply.parent_id]['reply'].append({
                'id': reply.pk,
                'post_id': reply.post_id,
                'add_time': reply.add_time,
                'content': reply.content,
                'parent_id': reply.parent_id,
                'reply_id': reply.reply_id,
                'nick': reply.nick,
                'to_nick': reply.to_nick,
                'browser': reply.browser,
                'client': reply.client,
                'avatar': reply.avatar,
            })
    comments_dict['count'] = len(replys) + len(comments)
    return comments_dict


# 博客文章列表页面
class Index(object):
    def __init__(self):
        # 定义 per_page 的值，每个页面的文章数
        self.per_page = 10

    def index(self, request):
        # 博客首页：获取Post表中所有文章列表
        post_list = Post.objects.filter(is_show=True, post_type='post')
        page = request.GET.get('page')
        return self.get_data(post_list=post_list, page=page, request=request)

    def tags(self, request, tag):
        # 标签：按照标签(tag)查询Post表中的文章列表
        post_list = Post.objects.filter(tags__name=tag, is_show=True, post_type='post')
        page = request.GET.get('page')
        return self.get_data(post_list=post_list, page=page, request=request)

    def get_data(self,post_list, page, request):
        post_list = self.Pagination(post_list=post_list, page=page)
        post_type = 'post'
        return render(request, 'blog/index.html', context={'post_list': post_list, 'post_type': post_type})

    # 高级分页扩展函数
    def Pagination(self, post_list, page):
        # 使用 Paginator 函数将post_list以每页per_page篇文章进行分页
        paginator = Paginator(post_list, self.per_page)
        try:
            post_list = paginator.page(page)
        except PageNotAnInteger:
            post_list = paginator.page(1)
        except EmptyPage:
            post_list = paginator.page(paginator.num_pages)
        return post_list


# 博客详情页
def Detail(request, pk):
    post = get_object_or_404(Post, pk=pk, is_show=True, post_type='post')
    post.increase_views()  # 调用 increase_views 方法，统计访问量
    comments_dict = comment_reply_content(post_id=pk)  # 评论回复
    comment_form = CommentForm()  # 引入评论表单
    context = {
        'post': post,
        'comments_dict': comments_dict,
        'comment_form': comment_form,
    }
    return render(request, 'blog/detail.html', context=context)


# 教程
def Tutorial(request):
    # 获取教程类型博文列表
    post_list = Post.objects.filter(is_show=True, post_type='post', tutorial__name__isnull=False).order_by('created_time')

    # 创建一个 dict, 以教程名称为关键字保存
    post_dict = {}
    for post in post_list:
        if post.tutorial not in post_dict.keys():
            post_dict[post.tutorial] = []
        post_dict[post.tutorial].append(post)
    return render(request, 'blog/tutorials.html', context={'post_dict': post_dict})


# 归档页面
def Archives(request):
    years = Post.objects.filter(is_show=True,post_type='post').dates('created_time', 'year', order='DESC')
    post_list = Post.objects.filter(is_show=True,post_type='post').order_by('-created_time')
    return render(request, 'blog/archives.html', context={'years': years, 'post_list':post_list})


# 关于页面
def About(request):
    post = Post.objects.filter(is_show=True, post_type='about').first()
    if post:
        post.increase_views()  # 调用 increase_views 方法，统计访问量
        comments_dict = comment_reply_content(post_id=post.id)  # 评论回复
        comment_form = CommentForm()  # 引入评论表单
        context = {
            'post': post,
            'comments_dict': comments_dict,
            'comment_form': comment_form,
        }
        return render(request, 'blog/about.html', context=context)
    else:
        return page_not_found(request)


# 我的项目
def Project(request):
    post = Post.objects.filter(is_show=True, post_type='project').first()
    if post:
        post.increase_views()  # 调用 increase_views 方法，统计访问量
        comments_dict = comment_reply_content(post_id=post.id)  # 评论回复
        comment_form = CommentForm()  # 引入评论表单
        context = {
            'post': post,
            'comments_dict': comments_dict,
            'comment_form': comment_form,
        }
        return render(request, 'blog/project.html', context=context)
    else:
        return page_not_found(request)

def chat_view(request):

    return render(request, 'blog/chat.html')

# 搜索请求
def search(request):
    # 搜索内容
    if request.method == 'GET':
        q = request.GET.get('q')
        post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q), is_show=True, post_type='post')

        data = {'posts': []}
        for post in post_list:
            data['posts'].append({
                "title": post.title,
                "permalink": post.get_absolute_url(),
                "text": post.body
            },)
        return HttpResponse(json.dumps(data,ensure_ascii=False), content_type="application/json,charset=utf-8")
    else:
        pass


class SparkAPI:
    def __init__(self):
        self.config = settings.SPARK_CONFIG

    def _generate_url(self):
        date = datetime.datetime.utcnow().strftime('%a, %d %b %Y %H:%M:%S GMT')
        signature_origin = f"host: {self.config['HOST']}\ndate: {date}\nGET {self.config['PATH']} HTTP/1.1"

        signature = base64.b64encode(
            hmac.new(
                self.config['API_SECRET'].encode('utf-8'),
                signature_origin.encode('utf-8'),
                digestmod='sha256'
            ).digest()
        ).decode()

        authorization_origin = (
            f'api_key="{self.config["API_KEY"]}", '
            f'algorithm="hmac-sha256", '
            f'headers="host date request-line", '
            f'signature="{signature}"'
        )

        authorization = base64.b64encode(authorization_origin.encode('utf-8')).decode()

        params = {
            'authorization': authorization,
            'date': date,
            'host': self.config['HOST']
        }

        return f"wss://{self.config['HOST']}{self.config['PATH']}?{urlencode(params)}"

    async def send_message(self, message):
        url = self._generate_url()
        async with websockets.connect(url) as ws:
            data = {
                "header": {
                    "app_id": self.config['APPID'],
                    "uid": "12345"
                },
                "parameter": {
                    "chat": {
                        "domain": "general",
                        "temperature": 0.5,
                        "max_tokens": 1024
                    }
                },
                "payload": {
                    "message": {
                        "text": [
                            {
                                "role": "user",
                                "content": message
                            }
                        ]
                    }
                }
            }

            await ws.send(json.dumps(data))

            response_text = ""
            async for response in ws:
                response_data = json.loads(response)
                if response_data["header"]["code"] != 0:
                    raise Exception(f"API请求错误: {response_data}")

                choices = response_data["payload"]["choices"]
                if choices.get("text"):
                    response_text += choices["text"][0]["content"]

                if response_data["header"]["status"] == 2:
                    break

            return response_text


# 聊天相关视图
def chat_view(request):
    return render(request, 'blog/chat.html')


@require_http_methods(["POST"])
@csrf_protect
async def send_message(request):
    try:
        data = json.loads(request.body)
        message = data.get('message', '').strip()

        if not message:
            return JsonResponse({'error': '消息不能为空'}, status=400)

        spark = SparkAPI()
        response = await spark.send_message(message)

        return JsonResponse({'response': response})

    except json.JSONDecodeError:
        return JsonResponse({'error': '无效的请求数据'}, status=400)
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)


import json
import websocket
import datetime
import hashlib
import base64
import hmac
import ssl
import time
from datetime import datetime

comment/views.py
# -*- coding: utf-8 -*-

from comment.models import Comment
from django.shortcuts import redirect
from django.views import View
from django.core.mail import EmailMultiAlternatives
import re
from www.settings import EMAIL_RECEIVE_LIST, EMAIL_HOST_USER


class CommentView(View):
    #  处理POST请求
    def post(self, request, post_id):
        comment = Comment()  # 实例化类
        comment.post_id = post_id
        comment.parent_id = request.POST['parent_id']
        comment.reply_id = request.POST['reply_id']
        comment.nick = request.POST['nick']
        comment.mail = request.POST['mail']
        comment.content = request.POST['content']

        ua = parse_user_agent(request.META.get('HTTP_USER_AGENT', ''))  # 解析HTTP_USER_AGENT
        comment.browser = ua['browser']
        comment.client = ua['client']

        # 处理回复评论
        if request.POST['reply_id'] != '0':
            comment.comment_type = 'reply'
            reply_comment = Comment.objects.filter(id=request.POST['reply_id']).first()
            if reply_comment:
                comment.to_nick = reply_comment.nick
                comment.to_mail = reply_comment.mail

                # 如果是回复评论，则发送邮件通知相关评论人
                recipient_list = EMAIL_RECEIVE_LIST + [reply_comment.mail]
            else:
                recipient_list = None
        else:
            # 如果是新的评论内容，则只需要发送通知博客作者
            recipient_list = EMAIL_RECEIVE_LIST

        comment.save()  # 保存评论数据到数据库

        redirect_url = request.POST['redirect_url'] + '#comment-{0}'.format(comment.id)
        if recipient_list:  # 发送邮件
            try:
                send_email(url=redirect_url, recipient_list=recipient_list, post_id=post_id)
            except BaseException as e:
                print('发送邮件错误: {}'.format(e))
        return redirect(redirect_url)  # 重定向到指定页面

    def get(self, request):
        pass


def send_email(url, recipient_list, post_id):
    """
    发送邮件
    :param url: 评论内容链接
    :param recipient_list: 邮件接收人
    :return: None
    """
    subject = '来自博客的留言'   # 邮件主题
    html_content = '<p>你好，你在博客中的留言有了新的回复内容! <a href="{0}" target="_blank">点击查看</a></p>'.format(url)  # 邮件正文
    msg = EmailMultiAlternatives(
        subject=subject,
        body=html_content,
        from_email=EMAIL_HOST_USER,
        to=recipient_list
    )

    msg.attach_alternative(html_content, "text/html")
    msg.send()  # 发送


# 解析User-Agent
def parse_user_agent(user_agent):
    browser = re.findall(r'([a-z]+/[0-9\.]+)[a-z ]*Safari/[0-9\.]+$', user_agent, re.I)
    if browser:
        browser = browser[0]

    else:
        browser = 'Unknown Browser'

    client = re.findall(r'^[a-z]+/\d*.?\d* \((.*?)\)', user_agent, re.I)
    if client:
        client = client[0]
    else:
        client = 'Unknown Client'

    return {
        'browser': browser,
        'client': client
    }

templates/blog/aside.html
{% load static %}
{% load blog_tags %}
{% get_site_configs as SITE_CONFIGS %}

<aside class="l_side">

    <!-- 侧边栏用户插件 -->
    <section class="author">
        <div class="content pure">
            <div class="avatar"><img class="avatar" src="{% static 'images/4dp8xm.jpg' %}"></div>
            <div class="text">
                <p>弃此残躯换清风，卷席苍穹复光年</p>
            </div>
            <div class="social-wrapper">
                <a href="mailto:{{ SITE_CONFIGS.email }}" class="social flat-btn waves-effect waves-button" target="_blank" rel="external"><i class="social fas fa-envelope" aria-hidden="true"></i></a>
                <a href="{{ SITE_CONFIGS.github }}" class="social flat-btn waves-effect waves-button" target="_blank" rel="external nofollow noopener noreferrer"><i class="social fab fa-github" aria-hidden="true"></i></a>
                <a href="{{ SITE_CONFIGS.weibo }}" class="social flat-btn waves-effect waves-button" target="_blank" rel="external nofollow noopener noreferrer"><i class="social fab fa-weibo" aria-hidden="true"></i></a>
                <a href="{{ SITE_CONFIGS.music }}" class="social flat-btn waves-effect waves-button" target="_blank" rel="external nofollow noopener noreferrer"><i class="social fas fa-headphones-alt" aria-hidden="true"></i></a>
            </div>
        </div>
    </section>


    <!-- 文章目录 -->
    <section class="toc-wrapper">
        <header class="pure toc-show-hide">
            <div><i id="toc-icon" class="fas fa-caret-down fa-fw" aria-hidden="true"></i>文章目录</div>
        </header>
        <div class="content pure" id="toc-content">
            <ol class="toc"></ol>
        </div>
    </section>



    <!-- 侧边栏热门标签插件 -->
    <section class="tagcloud">
        <header class="pure"><div><i class="fas fa-tags fa-fw" aria-hidden="true"></i>&nbsp;&nbsp;热门标签</div></header>
        <div class="content pure">
            {% get_tags as tags_list %}
            {% for tag in tags_list.tags %}
            <a href="{% url 'blog:tags' tag.name %}" style="" title="{{ tag.num_posts }}个话题">{{ tag.name }}({{ tag.num_posts }})</a>
            {% empty %}
                <a></a>
            {% endfor %}
        </div>
    </section>


    <!-- 侧边栏音乐插件 -->
    {% get_music as music %}
    {% if music %}
    <section class="music">
        <header class="pure">
            <div><i class="fas fa-compact-disc fa-fw" aria-hidden="true"></i>&nbsp;&nbsp;最近在听</div>
            <a class="rightBtn" target="_blank" rel="external nofollow noopener noreferrer" href="{{ music.home_url }}" title="{{ music.home_url }}"><i class="far fa-heart fa-fw"></i></a>
        </header>
        <div class="content pure">
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/aplayer@1.7.0/dist/APlayer.min.css">
            <div class="aplayer" {% if music.autoplay %}data-autoplay="true"{% endif %} data-theme="#1BCDFC" data-mode="{{ music.mode }}" data-server="{{ music.server }}" data-type="{{ music.type }}" data-id="{{ music.play_id }}" data-volume="0.7"></div>
            <script src="https://cdn.jsdelivr.net/npm/aplayer@1.7.0/dist/APlayer.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/meting@1.1.0/dist/Meting.min.js"></script>
        </div>
    </section>
    {% endif %}
</aside>
<script src="{% static 'js/aside.js' %}"></script>

templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}{{ SITE_CONFIGS.sitename }} - {{ post.title }}{% endblock %}

{% block l_main %}
<div class="l_main">
    <!-- 正文部分 -->
    <article id="post" class="post white-box article-type-post" itemscope="" itemprop="blogPost">
        <!-- 标题 -->
        <section class="meta">
            <div class="meta" id="header-meta">
                <h1 class="title">{{ post.title }}</h1>
                <div class="new-meta-box">
                    <div class="new-meta-item author"><a href="/blog"><i class="fas fa-user" aria-hidden="true"></i> {{ post.author }}</a></div>
                    <div class="new-meta-item date"><a class="notlink"><i class="fas fa-clock" aria-hidden="true"></i> {{ post.created_time | date:'Y-m-d H:i:s' }}</a></div>
                    <div class="new-meta-item browse busuanzi"><a class="notlink"><i class="fas fa-eye" aria-hidden="true"></i> <span id="busuanzi_value_page_pv">{{ post.views }}</span></a></div>
                </div>
                <hr>
            </div>
        </section>
        <!-- 正文 -->
        <section class="article typo">
            <div class="article-entry markdown-body" itemprop="articleBody" id="article_content">{{ post.body | safe }}</div>

            <section class="meta" id="footer-meta">
                <hr>
                <div class="new-meta-box">
                    {% for tag in post.tags.all %}
                    <div class="new-meta-item meta-tags"><a class="tag" href="{% url 'blog:tags' tag.name %}"><i class="fas fa-tag" aria-hidden="true"></i>&nbsp;{{ tag.name }}</a></div>
                    {% endfor %}
                    <div class="new-meta-item date" itemprop="dateUpdated">
                        <a class="notlink"><i class="fas fa-pencil-alt" aria-hidden="true"></i> {{ post.modified_time | date:'Y-m-d' }}</a>
                    </div>
                </div>
            </section>

            <div class="prev-next">
                {% if post.get_previous_field_by_created_time %}
                <section class="prev">
                    <span class="art-item-left">
                        <h4><a href="{{ post.get_previous_field_by_created_time.get_absolute_url }}" rel="prev" title="{{ post.get_previous_field_by_created_time.title }}"><i class="fas fa-chevron-left" aria-hidden="true"></i>&nbsp; {{ post.get_previous_field_by_created_time.title }}</a></h4>
                    </span>
                </section>
                {% endif %}
                {% if post.get_next_field_by_created_time %}
                <section class="next">
                    <span class="art-item-right" aria-hidden="true">
                        <h4><a href="{{ post.get_next_field_by_created_time.get_absolute_url }}" rel="prev" title="{{ post.get_next_field_by_created_time.title }}">{{ post.get_next_field_by_created_time.title }}&nbsp;<i class="fas fa-chevron-right" aria-hidden="true"></i></a></h4>
                    </span>
                </section>
                {% endif %}
            </div>
        </section>

    </article>
    <br>

    <!-- 评论区 -->
    {% include 'blog/comment.html' %}

</div>
{% endblock %}

templates/blog/header.html
<div id="loading-bar-wrapper" style="display: none;">
    <div id="loading-bar" class="pure" style="width: 100%;"></div>
</div>
<script>setLoadingBarProgress(20)</script>
<header class="l_header pure">
    <div class="wrapper">
        <div class="nav-main container container--flex">
            <a class="logo flat-box waves-effect waves-block" href="{% url 'blog:Index' %}">{{ SITE_CONFIGS.sitename }}的地球观测枢纽</a>
            <div class="menu">
                <ul class="h-list">
                    <li><a id="home" class="nav flat-box waves-effect waves-block" href="{% url 'home' %}"><i class="fas fa-home fa-fw"></i>&nbsp;主页</a></li>
                    <li><a id="blog" class="nav flat-box waves-effect waves-block" href="{% url 'blog:Index' %}"><i class="fas fa-rss fa-fw"></i>&nbsp;博客</a></li>
                    <li><a id="blogtutorial" class="nav flat-box waves-effect waves-block" href="{% url 'blog:Tutorial' %}"><i class="fas fa-book fa-fw"></i>教程</a></li>
                    <li><a id="blogarchives" class="nav flat-box waves-effect waves-block" href="{% url 'blog:Archives' %}"><i class="fas fa-archive fa-fw"></i>&nbsp;归档</a></li>
                    <li><a id="blogproject" class="nav flat-box waves-effect waves-block" href="{% url 'blog:Project' %}"><i class="fas fa-flask fa-fw"></i>&nbsp;项目</a></li>
                    <li><a id="blogabout" class="nav flat-box waves-effect waves-block" href="{% url 'blog:About' %}"><i class="fas fa-user fa-fw"></i>&nbsp;关于</a></li>
                    <li><a id="blogchat" class="nav flat-box waves-effect waves-block" href="{% url 'blog:chat' %}"><i class="fas fa-address-card fa-fw"></i>&nbsp;对话</a></li>
                </ul>
            </div>
            <div class="m_search">
                <form name="searchform" class="form u-search-form">
                    <input type="text" class="input u-search-input" placeholder="搜索">
                    <span class="icon"><i class="fas fa-search fa-fw"></i></span>
                </form>
            </div>
            <ul class="switcher h-list">
                <li class="s-search"><a class="fas fa-search fa-fw" href="javascript:void(0)"></a></li>
                <li class="s-menu"><a class="fas fa-bars fa-fw" href="javascript:void(0)"></a></li>
            </ul>
        </div>

        <div class="nav-sub container container--flex">
            <a class="logo flat-box waves-effect waves-block"></a>
            <ul class="switcher h-list">
                <li class="s-comment"><a class="flat-btn fas fa-comments fa-fw waves-effect waves-button" href="javascript:void(0)"></a></li>
                <li class="s-toc"><a class="flat-btn fas fa-list fa-fw waves-effect waves-button" href="javascript:void(0)"></a></li>
            </ul>
        </div>
    </div>
</header>
<aside class="menu-phone">
    <header>
        <nav class="menu">
            <ul>
                <li><a id="home" class="nav flat-box waves-effect waves-block" href="{% url 'home' %}"><i class="fas fa-home fa-fw"></i>&nbsp;主页</a></li>
                <li><a id="blog" class="nav flat-box waves-effect waves-block" href="{% url 'blog:Index' %}"><i class="fas fa-rss fa-fw"></i>&nbsp;博客</a></li>
                <li><a id="blogtutorial" class="nav flat-box waves-effect waves-block" href="{% url 'blog:Tutorial' %}"><i class="fas fa-book fa-fw"></i>教程</a></li>
                <li><a id="blogarchives" class="nav flat-box waves-effect waves-block" href="{% url 'blog:Archives' %}"><i class="fas fa-archive fa-fw"></i>&nbsp;归档</a></li>
                <li><a id="blogproject" class="nav flat-box waves-effect waves-block" href="{% url 'blog:Project' %}"><i class="fas fa-flask fa-fw"></i>&nbsp;项目</a></li>
                <li><a id="blogabout" class="nav flat-box waves-effect waves-block" href="{% url 'blog:About' %}"><i class="fas fa-user fa-fw"></i>&nbsp;关于</a></li>
                <li><a id="blogchat" class="nav flat-box waves-effect waves-block" href="{% url 'blog:chat' %}"><i class="fas fa-user fa-fw"></i>&nbsp;对话</a></li>
            </ul>
        </nav>
    </header>
</aside>